name: Aarambha
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter_secure_storage: ^9.2.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.5.1
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  intl: ^0.20.1
  url_launcher: ^6.1.8
  table_calendar: ^3.2.0
  provider: ^6.1.2
  google_sign_in: ^6.2.2
  cloud_functions: ^5.3.1
  firebase_data_connect: ^0.1.0
  firebase_app_check: ^0.3.2+1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
      - assets/images/logo.png
      - assets/images/aarambha.png
      - assets/images/aarambha-2.png
      - assets/icon/WhatsApp_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/aarambha-2.png"