name: gogglevue
description: "GoggleVue Dev version"

publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter_secure_storage: ^9.2.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.5.1
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  intl: ^0.20.1
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.2

  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icon/WhatsApp_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
