// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_VDp9a6oim3PtKlLdWF0HWMMQ84X5zP8',
    appId: '1:863514749149:ios:8b33e0170dba1254b19334',
    messagingSenderId: '863514749149',
    projectId: 'gogglevue',
    storageBucket: 'gogglevue.firebasestorage.app',
    iosBundleId: 'com.gogglevue.gogglevue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNaHl8Ms-IerKlgHiirQjgRw0pAihdJ4U',
    appId: '1:863514749149:web:3df092f8c2213939b19334',
    messagingSenderId: '863514749149',
    projectId: 'gogglevue',
    authDomain: 'gogglevue.firebaseapp.com',
    storageBucket: 'gogglevue.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNaHl8Ms-IerKlgHiirQjgRw0pAihdJ4U',
    appId: '1:863514749149:web:3df092f8c2213939b19334',
    messagingSenderId: '863514749149',
    projectId: 'gogglevue',
    authDomain: 'gogglevue.firebaseapp.com',
    storageBucket: 'gogglevue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_VDp9a6oim3PtKlLdWF0HWMMQ84X5zP8',
    appId: '1:863514749149:ios:2b344e8a16a69bcdb19334',
    messagingSenderId: '863514749149',
    projectId: 'gogglevue',
    storageBucket: 'gogglevue.firebasestorage.app',
    iosBundleId: 'com.gogglevue',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG8Rq-cG4xL7KdXreSsMAvuLf_Gx9UvuA',
    appId: '1:863514749149:android:5191d2c1f2b6493fb19334',
    messagingSenderId: '863514749149',
    projectId: 'gogglevue',
    storageBucket: 'gogglevue.firebasestorage.app',
  );

}